name: Python CI

on: [push, pull_request]

jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Linting läuft nur mit einer festen Version
          cache: "pip"

      - name: Install Black & Ruff
        run: pip install black ruff

      - name: Run Black
        run: black --check .

      - name: Run Ruff
        run: ruff check .

  test:
    name: Run Tests on Multiple Python Versions
    runs-on: ubuntu-latest
    needs: lint  # Tests starten nur, wenn Linting erfolgreich war
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]  # Hier alle unterstützen Versionen eintragen

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt pytest

      - name: Run Tests
        run: pytest
