name: Python CI

on: [push, pull_request]

jobs:
  lint-hard:
    name: Intrusive Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Linting läuft nur mit einer festen Version
          cache: "pip"

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff
        continue-on-error: true  # show warning instead of failing
        run: echo "::warning ruff check . --output-format github --select F,E,I,B,C4,UP,PERF,SIM,T20,PL --ignore E501 --line-length 100"
  
  lint-soft:
    name: Fundamental Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Linting läuft nur mit einer festen Version
          cache: "pip"

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff
        run: ruff check . --output-format github --line-length 100

  test:
    name: Run Tests on
    runs-on: ubuntu-latest
    #needs: lint  # only start if named job was successful
    strategy:
      matrix:
        # testing with currently popular python versions
        # 3.10 is lowest version that is supported by current pytest version
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt pytest

      - name: Run Tests
        run: python -m pytest
